### PR TITLE
added nested object and parameterised translations

### PR DESCRIPTION
**Pull request by KiranMantha**
1. added ability to traverse nested objects for translations
2. added abity to parameterise the translations

### CODE REVIEW

**Comment by KiranMantha** [comment]
please review and merge this change and release a new version to npm so that i can use in my project

**Comment by luiz-simples** [comment]
yeap

**Comment by luiz-simples** [comment]
vanilla-i18n@1.0.6

**Comment by KiranMantha** [comment]
Thanks Luiz

**Pull request merged**
